const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.AJAX,
		C3.Plugins.Function,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Spritefont2,
		C3.Plugins.Arr,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.NinePatch,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Acts.ScrollToObject,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgba,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Spritefont2.Exps.Height,
		C3.Plugins.Sprite.Exps.Width,
		C3.Behaviors.lunarray_LiteTween.Acts.SetTarget,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.trim,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnEnd,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.lunarray_LiteTween.Acts.SetDuration,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Acts.SetPosToObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.Text.Acts.SetPos,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.lunarray_LiteTween.Exps.Progress,
		C3.Behaviors.lunarray_LiteTween.Acts.ProgressTo,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Spritefont2.Exps.UID,
		C3.Plugins.Spritefont2.Exps.BBoxTop,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.Signal,
		C3.JavaScriptInEvents.Es_game_Event30_Act10,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Spritefont2.Cnds.PickByUID,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetZElevation,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.OnSignal,
		C3.JavaScriptInEvents.Es_game_Event60_Act1,
		C3.JavaScriptInEvents.Es_loader_Event2_Act1,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Exps.BBoxLeft,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.System.Cnds.OnLoadFinished
	];
};
self.C3_JsPropNameTable = [
	{AJAX: 0},
	{Function: 0},
	{Browser: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{guide: 0},
	{bg: 0},
	{Sine: 0},
	{btnStart: 0},
	{appTittle: 0},
	{Touch: 0},
	{scorePanel: 0},
	{lifesPanel: 0},
	{choice1Button: 0},
	{lifes: 0},
	{txtLifes: 0},
	{txtScore: 0},
	{scoreTxt1: 0},
	{choice2Button: 0},
	{choice3Button: 0},
	{choice4Button: 0},
	{questionsArray: 0},
	{txtChoice11: 0},
	{txtChoice2: 0},
	{txtChoice3: 0},
	{txtChoice4: 0},
	{txtQuestion1: 0},
	{used: 0},
	{pos1: 0},
	{active: 0},
	{open: 0},
	{close: 0},
	{gameOverPopup: 0},
	{btnHome: 0},
	{btnRetry: 0},
	{txtFInalScore1: 0},
	{finalScoreTxt: 0},
	{pos2: 0},
	{pos3: 0},
	{pos4: 0},
	{txtHighscore: 0},
	{optionPanel: 0},
	{openOpt: 0},
	{musicOpt: 0},
	{resetOpt: 0},
	{deco: 0},
	{mode: 0},
	{LiteTween: 0},
	{timerBar: 0},
	{timerBarPos: 0},
	{comboPanel: 0},
	{comboTimerBar: 0},
	{comboTimerPos: 0},
	{comboTxt1: 0},
	{loadingBarPos: 0},
	{loadingBar: 0},
	{watermark: 0},
	{Jiffy: 0},
	{Asset2: 0},
	{Text2: 0},
	{iconComboPanel: 0},
	{iconTimerCt: 0},
	{txtCountDown1: 0},
	{txtQuestion: 0},
	{txtCountDown: 0},
	{Text: 0},
	{Text3: 0},
	{scoreTxt: 0},
	{txtFInalScore: 0},
	{txtChoice1: 0},
	{comboTxt: 0},
	{choicePositions: 0},
	{choiceButtons: 0},
	{sprites: 0},
	{fontInBackground: 0},
	{timerAndCombo: 0},
	{fontInPanel: 0},
	{choiceTexts: 0},
	{loadingBars: 0},
	{highscore: 0},
	{music: 0},
	{VPTOP: 0},
	{VPBOTTOM: 0},
	{VPLEFT: 0},
	{VPRIGHT: 0},
	{totalQuestion: 0},
	{index: 0},
	{comboTimer: 0},
	{comboMultiplier: 0},
	{currentQuestionIndex: 0},
	{answer: 0},
	{Score: 0},
	{timer: 0},
	{bonus_time: 0},
	{currentIndex: 0},
	{tempValue: 0},
	{randomIndex: 0},
	{ID_game: 0},
	{params: 0},
	{mobileNumber: 0},
	{token: 0},
	{transactionID: 0},
	{gamemodeID: 0}
];

self.InstanceType = {
	AJAX: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	guide: class extends self.ISpriteInstance {},
	bg: class extends self.ISpriteInstance {},
	btnStart: class extends self.ISpriteInstance {},
	appTittle: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	scorePanel: class extends self.ISpriteInstance {},
	lifesPanel: class extends self.ISpriteInstance {},
	choice1Button: class extends self.ISpriteInstance {},
	lifes: class extends self.ISpriteInstance {},
	txtLifes: class extends self.ISpriteFontInstance {},
	txtScore: class extends self.ISpriteFontInstance {},
	scoreTxt1: class extends self.ISpriteFontInstance {},
	choice2Button: class extends self.ISpriteInstance {},
	choice3Button: class extends self.ISpriteInstance {},
	choice4Button: class extends self.ISpriteInstance {},
	questionsArray: class extends self.IArrayInstance {},
	txtChoice11: class extends self.ISpriteFontInstance {},
	txtChoice2: class extends self.ISpriteFontInstance {},
	txtChoice3: class extends self.ISpriteFontInstance {},
	txtChoice4: class extends self.ISpriteFontInstance {},
	txtQuestion1: class extends self.ISpriteFontInstance {},
	pos1: class extends self.ISpriteInstance {},
	gameOverPopup: class extends self.ISpriteInstance {},
	btnHome: class extends self.ISpriteInstance {},
	btnRetry: class extends self.ISpriteInstance {},
	txtFInalScore1: class extends self.ISpriteFontInstance {},
	finalScoreTxt: class extends self.ISpriteFontInstance {},
	pos2: class extends self.ISpriteInstance {},
	pos3: class extends self.ISpriteInstance {},
	pos4: class extends self.ISpriteInstance {},
	txtHighscore: class extends self.ISpriteFontInstance {},
	optionPanel: class extends self.ISpriteInstance {},
	openOpt: class extends self.ISpriteInstance {},
	musicOpt: class extends self.ISpriteInstance {},
	resetOpt: class extends self.ISpriteInstance {},
	deco: class extends self.ISpriteInstance {},
	mode: class extends self.ISpriteInstance {},
	timerBar: class extends self.IWorldInstance {},
	timerBarPos: class extends self.IWorldInstance {},
	comboPanel: class extends self.IWorldInstance {},
	comboTimerBar: class extends self.IWorldInstance {},
	comboTimerPos: class extends self.IWorldInstance {},
	comboTxt1: class extends self.ISpriteFontInstance {},
	loadingBarPos: class extends self.ITiledBackgroundInstance {},
	loadingBar: class extends self.ITiledBackgroundInstance {},
	watermark: class extends self.ISpriteFontInstance {},
	Jiffy: class extends self.ISpriteInstance {},
	Asset2: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	iconComboPanel: class extends self.ISpriteInstance {},
	iconTimerCt: class extends self.ISpriteInstance {},
	txtCountDown1: class extends self.ISpriteFontInstance {},
	txtQuestion: class extends self.ITextInstance {},
	txtCountDown: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	scoreTxt: class extends self.ITextInstance {},
	txtFInalScore: class extends self.ITextInstance {},
	txtChoice1: class extends self.ITextInstance {},
	comboTxt: class extends self.ITextInstance {},
	choicePositions: class extends self.ISpriteInstance {},
	choiceButtons: class extends self.ISpriteInstance {},
	sprites: class extends self.ISpriteInstance {},
	fontInBackground: class extends self.ISpriteFontInstance {},
	timerAndCombo: class extends self.IWorldInstance {},
	fontInPanel: class extends self.ISpriteFontInstance {},
	choiceTexts: class extends self.ISpriteFontInstance {},
	loadingBars: class extends self.ITiledBackgroundInstance {}
}